# Site settings
title: ForkonLP
email: forkonlp@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

slack_username: forkonlpforslack
github_username: mrchypark

# Build settings
markdown: kramdown
